'use client';

import { useState, useEffect, useRef } from 'react';
import type { AssetSymbol, StrategyRuleSet } from '@/types/strategy';
import type { BacktestResult, RunSnapshot } from '@/types/results';
import { ResultsHeader } from '@/components/ResultsHeader';
import { ExportToolbar } from '@/components/ExportToolbar';
import { MetricsGrid } from '@/components/MetricsGrid';
import { ComparisonView } from '@/components/ComparisonView';
import { EquityCurve } from '@/components/EquityCurve';
import { ChartWithData } from '@/components/ChartWithData';
import { WarmupWarning } from '@/components/WarmupWarning';
import { TradeLog } from '@/components/TradeLog';
import { AuditPanel } from '@/components/AuditPanel';
import { CompareSection } from '@/components/CompareSection';
import { RunHistory } from '@/components/RunHistory';
import { SlidePanel } from '@/components/SlidePanel';
import { RuleConfirmation } from '@/components/RuleConfirmation';

export function ResultsPhase({
  result,
  comparisonResult,
  strategyName,
  activeAsset,
  isComparing,
  runHistory,
  rules,
  onAssetSwap,
  onClearComparison,
  onCompareWithPrompt,
  onCompareWithPreset,
  onRestore,
}: {
  result: BacktestResult;
  comparisonResult: BacktestResult | null;
  strategyName: string;
  activeAsset: AssetSymbol;
  isComparing: boolean;
  runHistory: RunSnapshot[];
  rules: StrategyRuleSet | null;
  onAssetSwap: (asset: AssetSymbol) => void;
  onClearComparison: () => void;
  onCompareWithPrompt: (prompt: string) => void;
  onCompareWithPreset: (ruleSet: StrategyRuleSet) => void;
  onRestore: (result: BacktestResult) => void;
}) {
  const [rulesOpen, setRulesOpen] = useState(false);
  const autoOpenedRef = useRef(false);

  // Auto-open drawer on low confidence parse
  useEffect(() => {
    if (rules?.metadata?.parserConfidence === 'low' && !autoOpenedRef.current) {
      autoOpenedRef.current = true;
      setRulesOpen(true);
    }
  }, [rules]);
  return (
    <div className="space-y-6">
      <ResultsHeader
        result={result}
        strategyName={strategyName}
        activeAsset={activeAsset}
        onAssetSwap={onAssetSwap}
        onViewRules={rules ? () => setRulesOpen(true) : undefined}
      />

      <ExportToolbar result={result} />

      <MetricsGrid metrics={result.metrics} benchmarkReturn={result.benchmark.totalReturn} />

      {comparisonResult && (
        <div className="space-y-2">
          <div className="flex items-center justify-end">
            <button
              onClick={onClearComparison}
              className="text-xs text-slate-500 hover:text-slate-300 transition-colors"
            >
              Remove Comparison
            </button>
          </div>
          <ComparisonView resultA={result} resultB={comparisonResult} />
        </div>
      )}

      <div>
        <h3 className="text-sm font-medium text-vt-dim/70 mb-2 uppercase tracking-wider">
          Equity Curve
        </h3>
        <EquityCurve equityCurve={result.equityCurve} />
      </div>

      <div>
        <h3 className="text-sm font-medium text-vt-dim/70 mb-2 uppercase tracking-wider">
          Price Chart
        </h3>
        <ChartWithData
          asset={result.config.asset}
          startDate={result.config.startDate}
          endDate={result.config.endDate}
          trades={result.trades}
          indicatorData={result.indicatorData}
        />
      </div>

      {result.trades.length === 0 && <WarmupWarning audit={result.audit} />}

      <div>
        <h3 className="text-sm font-medium text-vt-dim/70 mb-2 uppercase tracking-wider">
          Trade Log ({result.trades.length} trades)
        </h3>
        {result.trades.length === 0 ? (
          <div className="rounded-lg border border-vt-line/50 bg-vt-bg3/20 p-6 text-center">
            <p className="text-slate-400">No trades were generated by this strategy.</p>
            <p className="text-xs text-slate-600 mt-1">
              Try adjusting the indicator parameters or date range.
            </p>
          </div>
        ) : (
          <TradeLog trades={result.trades} />
        )}
      </div>

      <AuditPanel audit={result.audit} />

      {!comparisonResult && (
        <CompareSection
          isComparing={isComparing}
          onCompareWithPrompt={onCompareWithPrompt}
          onCompareWithPreset={onCompareWithPreset}
        />
      )}

      {runHistory.length > 0 && (
        <RunHistory history={runHistory} onRestore={onRestore} />
      )}

      {rules && (
        <SlidePanel
          isOpen={rulesOpen}
          onClose={() => setRulesOpen(false)}
          title="Strategy Rules"
          wide
        >
          <RuleConfirmation rules={rules} readOnly />
        </SlidePanel>
      )}
    </div>
  );
}
